return {
  {
    id = "modern_start_menu_ui",
    key = "start_menu",
    name = "Modern Start Menu",
    short = "START",
    version = "0.1.18",
    installOrder = 5,
    files = { "main.lua", "screen.lua", "settings.lua", "icons.lua" },
    assets = { "assets/start_menu_icons.png" },
    legacyExtras = { "icons" },
  },
  {
    id = "modern_party_ui",
    key = "party",
    name = "Modern Party UI",
    short = "PARTY",
    version = "0.4.9",
    installOrder = 3,
    files = {
      "main.lua", "screen.lua", "summary.lua", "party_tools.lua",
      "ribbons.lua", "gen2.lua",
    },
  },
  {
    id = "modern_bag_ui",
    key = "bag",
    name = "Modern Bag UI",
    short = "BAG",
    version = "0.5.0",
    installOrder = 1,
    files = { "main.lua", "screen.lua", "inventory.lua", "gen2.lua" },
    assets = { "assets/classic_bag_pockets.png" },
  },
  {
    id = "modern_pc_ui",
    key = "pc",
    name = "Modern PC UI",
    short = "PC",
    version = "0.4.3",
    installOrder = 6,
    files = { "main.lua", "screen.lua", "gen2.lua" },
  },
  {
    id = "modern_pokedex_ui",
    key = "pokedex",
    name = "Modern Pokedex UI",
    short = "POKEDEX",
    version = "0.2.10",
    installOrder = 7,
    files = { "main.lua", "screen.lua", "gen2.lua" },
  },
  {
    id = "battle_info_hud",
    key = "battle_hud",
    name = "Battle Info HUD",
    short = "BATTLE HUD",
    version = "0.9.2",
    installOrder = 2,
    enabledOption = "enabled",
    files = { "main.lua", "hud.lua", "gen2.lua" },
  },
  {
    id = "typed_move_colors",
    key = "move_colors",
    name = "Typed Move Colors",
    short = "MOVE COLORS",
    version = "0.4.8",
    installOrder = 4,
    files = { "main.lua", "ui.lua", "gen2.lua" },
  },
}
